<?php

namespace MariageBundle\Repository;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTrajetsProposes()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT t FROM MariageBundle:Trajet t WHERE t.voiture IS NOT NULL'
        );
        return $query->getResult();
    }

    public function getTrajetsDemandes()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT t FROM MariageBundle:Trajet t WHERE t.voiture IS NULL'
        );
        return $query->getResult();
    }
}
